# Generated by Django 2.1.5 on 2020-08-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200802_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to='network.UserProfile'),
        ),
    ]
